<h1>Vložte nový kontakt</h1>



<form method="post" id="new-form">
    Jméno a příjmení<br />
    <input type="text" name="name" required="required" /><br />
    Telefon<br />
    <input type="tel" name="tel" required="required" /><br />
    Email<br />
    <input type="email" name="mail" required="required" value="" /><br />
    Poznámka<br />
    <textarea name="note"></textarea><br />
    <input type="submit" value="Vložit" />
</form>
<br>

<a href="/"> Zpět bez uložení</a>