<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <meta charset="UTF-8" />
    <title>Adresář</title>
    <meta name="description" content="Toto je adresář kontaktů pro Modrého Ducha" />
    <meta name="keywords" content="Adresář, Modrý Duch, PHP" />
</head>

<body>
<header>
    <h1>Adresář pro Modrého Ducha</h1>
</header>


    <?php $this->calledController->showView(); // Vložení pohledu?>


</body>
</html>